---
# tasks file for roles/basedeps

- name: system packages | install epel repo
  become: true
  yum:
    name: epel-release
    state: present

- name: system packages | basic system utils
  become: true
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - patch
    - redhat-lsb-core
    - rsync
    - tar
    - unzip
    - wget
    - zip
