---
# tasks file for roles/basedeps

- name: system packages | install epel repo
  become: true
  ansible.builtin.yum:
    name: epel-release
    state: present
  when: ansible_os_family == 'RedHat'

# use separate yum/apt tasks because package only installs one item at a time

- name: system packages | basic system utils (centos)
  become: true
  ansible.builtin.yum:
    name: "{{ basedeps_packages }}"
    state: present
  when: ansible_os_family == 'RedHat'

- name: system packages | basic system utils (ubuntu)
  become: true
  ansible.builtin.apt:
    name: "{{ basedeps_packages }}"
    state: present
  when: ansible_os_family == 'Debian'

- name: system packages | lsb
  become: true
  ansible.builtin.package:
    name: "{{ basedeps_lsb_package[ansible_os_family] }}"
    state: present
  when: basedeps_install_lsb
