---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: centos-7
    image: centos:7
  - name: ubuntu-1804
    image: ubuntu:18.04
  - name: ubuntu-2004
    image: ubuntu:20.04
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
